### ISSUE TITLE
Change card dropper priority to only when dropper reacts in <2s

### ISSUE THREAD

**Issue by lucamotion** [dreamingkills/zephyr#44]

**Comment by ManmanLv1** [comment]
No, or at least 2 sec is too short
first, some player with low internet collection may not load pic on time but that can fix with better internet anyway
second, device disadvantage, if you use PC , it's fine but if you on phone ,chat is very flood and other can spam massage so dropper can't find their drop and miss that opportunity

**Comment by lucamotion** [comment]
not really a problem
